#!/bin/bash
# set -e

# personal workjam token
export MY_TOKEN=eyJraWQiOiJXT1JLSkFNLUFQSS1HQVRFV0FZLUtFWS1JRCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIyMDAwMDQ2MDE5MzcwIiwiZmlyc3ROYW1lIjoiSGFtZGFuIiwibGFzdE5hbWUiOiJNYWhtb29kIiwiaXNXSkFkbWluIjpmYWxzZSwiZW50cm9weSI6NzYwNTIzMzk5NDc4NTUyNTI3NiwiaXNzIjoidW5rbm93biIsImRhdGFjZW50ZXJJZCI6ImdjcC1hdXMiLCJleHAiOjE3NzYwNTE0MTMsImlhdCI6MTc3MDg2NzM1MywiaXNYVG9rZW4iOnRydWV9.18NpP9QYLW829PPBTzOZXTMTwK9PpJEo9BuIsM2rdBxSghfWT_3grfhMC7xRr0jDsrnMkrqFV4xJzUHbBgnNPt2SRuvQMjt9O8II6xtGWqwCVbg7C8DggJrrXBt19PQevjpobb2pU6AJu-C8p72-3zFSE8detbki_E87btsWv_cq5c6CkTgOXy6k9E9NoMojc3lNiZ09jUC5i7Uzf_Gg7hcdU5bEiPyMQt9io0d0Mq6Sc5HRgTOmmMwhLlVd1b4zlJfpCYMlSC7-FbjXJsvMgvQZO-wTolwnpAN-40iZkRvT5Baw_qupYll_G39oDvsZ5vAqCy_Kh0ukg75OxIvYBA

# build script
export ZIG_GLOBAL_CACHE_DIR=$PWD/target/zig-cache # [src](https://github.com/ziglang/zig/issues/19400) - global cache in home by default for Zig

cargo zigbuild --release --target aarch64-unknown-linux-gnu
ssh hamdan@rasso.local "killall mtxshift"
scp target/aarch64-unknown-linux-gnu/release/mtxshift hamdan@rasso.local:~
ssh hamdan@rasso.local "~/mtxshift"